version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    target-branch: "main"
    labels:
      - "dependencies"
      - "pnpm"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "build"
      prefix-development: "build(deps)"
      include: "scope"
    groups:
      patch-updates:
        update-types:
          - "patch"
          - "minor"
